[loggers]
keys=root,app,streamlit.runtime,streamlit.watcher

[handlers]
keys=console

[formatters]
keys=precise

[logger_root]
level=WARNING
handlers=console

[logger_app]
level=DEBUG
handlers=console
qualname=app
propagate=0

[logger_streamlit.runtime]
level=ERROR
handlers=console
qualname=streamlit.runtime
propagate=0

[logger_streamlit.watcher]
level=ERROR
handlers=console
qualname=streamlit.watcher
propagate=0

[handler_console]
class=StreamHandler
level=DEBUG
formatter=precise
args=(sys.stderr,)

[formatter_precise]
format=%(asctime)s [%(levelname)-8s] %(name)s — %(message)s
datefmt=%H:%M:%S
